### ISSUE TITLE
Add the possibility to implement a scheduler for the examples creation

### ISSUE THREAD

**Issue by matteogabburo** [iKernels/transformers-lightning#35]
At the moment the creation of the examples made by the adapters is stateless. I'm proposing to add to the datamodule and then to the the adapters, some informations taken directly from the trainer, for example the ```trainer.global_step``` parameter.

This parameter could be used to prepare a scheduler that handles the data creation, before the trainingstep. This approach could have different benefits, first of all a speedup of the training since the data preparation will be totally leaved to the cpu workers.

**Comment by matteogabburo** [comment]
I implemented the proposed solution in https://github.com/lucadiliello/transformers-lightning/tree/feat-%2335

**Comment by lucadiliello** [comment]
Proposed solution does not work at the moment because with many workers that parse a dataset you receive a static copy of the trainer parameters.
